<?php

declare(strict_types=1);

namespace OxidSupport\ModulePerformance\Twig\Loader;

use OxidEsales\Twig\Loader\FilesystemLoader as CoreFilesystemLoader;
use OxidEsales\Twig\Resolver\TemplateDirectoryResolverAggregate;
use Twig\Loader\LoaderInterface;
use Twig\Source;
use Twig\Error\LoaderError;


class FilesystemLoader extends CoreFilesystemLoader
{
    /** @var array<string, string> */
    private array $templateMap = [];

    /** @var array<string, string> */
    private array $resolveCache = [];

    public function __construct(
        private TemplateDirectoryResolverAggregate $templateDirectoryResolver,
        private string $templateMapFile
    ) {
        if (is_file($this->templateMapFile)) {
            $map = require $this->templateMapFile;
            if (is_array($map)) {
                $this->templateMap = $map;
            }
        }

        // Always ensure that templates for the *current* context
        // (e.g. admin_twig, apex, other themes) are present in the map.
        // This allows different contexts to gradually contribute to the
        // same map file instead of the first one "locking" the contents.
        $this->templateMap = $this->buildMapAtRuntime($this->templateMap);

    }

    public function getSourceContext(string $name): Source
    {
        $path = $this->resolvePath($name);

        $code = @file_get_contents($path);
        if ($code === false) {
            throw new LoaderError(sprintf(
                'Unable to read template "%s" at "%s".',
                $name,
                $path
            ));
        }

        return new Source($code, $name, $path);
    }

    public function getCacheKey(string $name): string
    {
        return $this->resolvePath($name);
    }

    public function exists(string $name): bool
    {
        $normalized = $this->normalizeName($name);

        if (isset($this->resolveCache[$normalized])) {
            return true;
        }

        return isset($this->templateMap[$normalized]);
    }

    public function isFresh(string $name, int $time): bool
    {
        // In production the map is generated by command / runtime and is treated as final.
        return true;
    }

    private function resolvePath(string $name): string
    {
        $normalized = $this->normalizeName($name);

        if (isset($this->resolveCache[$normalized])) {
            return $this->resolveCache[$normalized];
        }

        if (!isset($this->templateMap[$normalized])) {
            throw new LoaderError(sprintf('Template "%s" is not defined.', $name));
        }

        return $this->resolveCache[$normalized] = $this->templateMap[$normalized];
    }

    /**
     * Fallback when there is no pre-generated template map.
     * Builds the map once at runtime and persists it to disk.
     */
    private function buildMapAtRuntime(array $existingMap = []): array
    {
        $map = $existingMap;

        foreach ($this->templateDirectoryResolver->getTemplateDirectories() as $namespacedDirectory) {
            $namespace = $namespacedDirectory->getNamespace();
            $dir = rtrim($namespacedDirectory->getDirectory(), DIRECTORY_SEPARATOR);

            if (!is_dir($dir)) {
                continue;
            }

            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator(
                    $dir,
                    \FilesystemIterator::SKIP_DOTS | \FilesystemIterator::FOLLOW_SYMLINKS
                )
            );

            foreach ($iterator as $file) {
                if (!$file->isFile()) {
                    continue;
                }

                $ext = strtolower($file->getExtension());
                if (!in_array($ext, ['twig', 'svg', 'tpl'], true)) {
                    continue;
                }

                $relativePath = ltrim(str_replace($dir, '', $file->getPathname()), DIRECTORY_SEPARATOR);

                $mainKey = '@__main__/' . $relativePath;
                if (!isset($map[$mainKey])) {
                    $map[$mainKey] = $file->getPathname();
                }

                if ($namespace !== null && $namespace !== '') {
                    $namespacedKey = sprintf('@%s/%s', $namespace, $relativePath);
                    if (!isset($map[$namespacedKey])) {
                        $map[$namespacedKey] = $file->getPathname();
                    }
                }
            }
        }

        @file_put_contents(
            $this->templateMapFile,
            '<?php return ' . var_export($map, true) . ';'
        );

        return $map;
    }

    private function normalizeName(string $name): string
    {
        $name = ltrim($name, '/');

        if ($name !== '' && $name[0] === '@') {
            return $name;
        }

        return '@__main__/' . $name;
    }
}
